### ISSUE TITLE
关于翻译的相关问题的讨论

### ISSUE THREAD

**Issue by awxiaoxian2020** [vanchKong/vitepress#4]
翻译的格式应遵循https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5

**Comment by awxiaoxian2020** [comment]
@vanchKong 哪一个提交更新了内容被我新合并的内容覆盖了，麻烦贴一下链接~

**Comment by vanchKong** [comment]
https://github.com/vanchKong/vitepress/commit/c045f5b16e5f2ab9daa579d635c6e52b844cc21f
是需要这个吗 @awxiaoxian2020

**Comment by awxiaoxian2020** [comment]
https://github.com/vanchKong/vitepress/pull/5/commits/f220325f909fd7eb0dfde3153535ccbdf34f173f

这个提交你又修改了config.ts的格式，我已经将其还原。
